source = { statement* }
statement = _{ assignment | function_call }
assignment = { symbol_ref ~ "=" ~ value }
expression = _{ value | function_call }

function_call = { symbol_ref ~ "(" ~ fn_args? ~ ")"}
fn_args = { fn_arg ~ ("," ~ fn_arg )* }
fn_arg = _{ expression }


symbol_ref = { ASCII_ALPHA ~ (ASCII_ALPHANUMERIC|"_")* }
value = { string }

string = ${ "\"" ~ string_value ~ "\"" }
string_value = @{ char* }
char = {
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

WHITESPACE = _{" " | NEWLINE}